site_name:  NLP UYGULAMALARINDA VERİ GİZLİLİĞİ VE KARŞILAŞILAN ETİK SORUNLAR


repo_name: NLPsEthicsPrivacy
repo_url: https://github.com/alpd4/NLPsEthicsPrivacy/
edit_uri: 'https://github.com/alpd4/NLPsEthicsPrivacy/tree/main/nlpethicsandprivacy/docs'
